version: '2'
services:
  api:
    container_name: api.xxxxxx.com.local
    image: abibao/api-gateway:rece
    privileged: true
    volumes:
      - ./docker/volumes/logs/web:/logs
    environment:
        - ABIBAO_API_GATEWAY_EXPOSE_IP=localhost
        - ABIBAO_API_GATEWAY_EXPOSE_PORT=80,
        - ABIBAO_API_GATEWAY_SERVER_AUTH_BASIC_PASSWORD=abibao#2015
        - ABIBAO_API_GATEWAY_SERVER_AUTH_BASIC_USERNAME=abibao
        - ABIBAO_API_GATEWAY_SERVER_AUTH_JWT_KEY=AUTH_8UR40M2nQ8leURX262xY0OokvfhQunG4
        - ABIBAO_API_GATEWAY_LOGS_FILE=/logs/api-deve-gateway.log
        - ABIBAO_API_GATEWAY_NEWRELIC_APPNAME=api.deve.abibao.com
        - ABIBAO_API_GATEWAY_LOGSTASH_HOST=logstash.xxxxxx.com.local
        - ABIBAO_API_GATEWAY_LOGSTASH_PORT=5001,
        - ABIBAO_API_GATEWAY_RABBITMQ_URL=amqp://admin:uaLEm6NmTpK3t2mRCSrS@rabbitmq.xxxxxx.com.local:5672
        - ABIBAO_API_GATEWAY_RABBITMQ_ENV=deve
        - ABIBAO_API_GATEWAY_SERVER_RETHINK_HOST=rethinkdb.xxxxxx.com.local
        - ABIBAO_API_GATEWAY_SERVER_RETHINK_PORT=28015,
        - ABIBAO_API_GATEWAY_SERVER_RETHINK_AUTH_KEY=8UR40M2nQ8leURX262xY0OokvfhQunG4
        - ABIBAO_API_GATEWAY_SERVER_RETHINK_DB=mvp_deve
        - ABIBAO_API_GATEWAY_SERVER_MYSQL_HOST=mysql.xxxxxx.com.local
        - ABIBAO_API_GATEWAY_SERVER_MYSQL_PORT=3306
        - ABIBAO_API_GATEWAY_SERVER_MYSQL_USER=admin
        - ABIBAO_API_GATEWAY_SERVER_MYSQL_PASSWORD=zh2y5Xtjt4TkJB8HgsWK
        - ABIBAO_API_GATEWAY_SERVER_MYSQL_DATABASE=analytics_deve
        - ABIBAO_API_GATEWAY_SENDGRID_API_KEY=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
        - ABIBAO_API_GATEWAY_SENDGRID_TEMPLATE_ABIBAO_AFFECT_CAMPAIGNS_AUTO=7089447c-fce6-4e80-9050-5dc14e98dd4b
        - ABIBAO_API_GATEWAY_SENDGRID_ASM_GROUP_ID_ABIBAO_AFFECT_CAMPAIGNS_AUTO=653,
        - ABIBAO_API_GATEWAY_SLACK_WEBHOOK=https://hooks.slack.com/services/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
        - ABIBAO_API_GATEWAY_URI=http://api.xxxxxx.com.local
        - ABIBAO_WEB_DASHBOARD_URI=http://dashboard.xxxxxx.com.local
    links:
      - rabbitmq
      - rethinkdb
      - mysql
      - logstash
  rabbitmq:
    container_name: rabbitmq.xxxxxx.com.local
    image: rabbitmq:3.6.2-management
    privileged: true
    volumes:
      - ./docker/volumes/local/rabbitmq:/var/lib/rabbitmq
    environment:
      - RABBITMQ_DEFAULT_USER=admin
      - RABBITMQ_DEFAULT_PASS=uaLEm6NmTpK3t2mRCSrS
  rethinkdb:
    container_name: rethinkdb.xxxxxx.com.local
    image: rethinkdb:2.3.3
    privileged: true
    volumes:
      - ./docker/volumes/local/rethinkdb:/data
  mysql:
    container_name: mysql.xxxxxx.com.local
    image: mysql/mysql-server:5.7.12
    privileged: true
    volumes:
      - ./docker/volumes/local/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=p6s9rXdVnfxGcX9UZck8
      - MYSQL_USER=admin
      - MYSQL_PASSWORD=zh2y5Xtjt4TkJB8HgsWK
      - MYSQL_DATABASE=xxxxxx
  elasticsearch:
    container_name: elasticsearch.xxxxxx.com.local
    image: elasticsearch:2.3.3
    privileged: true
    volumes:
      - ./docker/volumes/local/elasticsearch:/usr/share/elasticsearch/data
    command: elasticsearch -Des.network.host=0.0.0.0
  logstash:
    container_name: logstash.xxxxxx.com.local
    image: logstash:2.3.2-1
    privileged: true
    command: logstash -f /etc/logstash/conf.d/logstash.conf
    volumes:
      - ./docker/logstash/config:/etc/logstash/conf.d
  kibana:
    container_name: kibana.xxxxxx.com.local
    build: docker/kibana/
    privileged: true
    volumes:
      - ./docker/kibana/config/:/opt/kibana/config/
